# Generated by Django 3.1.6 on 2021-03-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.DateTimeField(verbose_name='Время начала маршрута')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания маршрута')),
                ('money', models.PositiveIntegerField(verbose_name='Наличный расчет')),
                ('red', models.PositiveIntegerField(verbose_name='Красный валидатор')),
                ('black', models.PositiveIntegerField(verbose_name='Чёрный валидатор')),
                ('km', models.PositiveIntegerField(verbose_name='Пробег (В РАЗРАБОТКЕ)')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.car', verbose_name='Транспорт')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Auth.driver', verbose_name='Водитель')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
                'db_table': 'surveys',
            },
        ),
    ]
